# These are supported funding model platforms

github: [yourusername]
# Custom funding links
custom: ['https://paypal.me/yourusername', 'https://ko-fi.com/yourusername']
# Open Collective
open_collective: blips
# Otechie
otechie: yourusername
# Patreon
patreon: yourusername
# Tidelift
tidelift: blips
# Community Bridge
community_bridge: blips
# IssueHunt
issuehunt: yourusername
# Ko-fi
ko_fi: yourusername
# Liberapay
liberapay: yourusername
# Buy Me a Coffee
buymeacoffee: yourusername
# GitHub Sponsors
github: [yourusername]
# Custom funding links
custom: ['https://paypal.me/yourusername', 'https://ko-fi.com/yourusername'] 