name: BLiPS
options:
  bundleIdPrefix: com.blips
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  BLiPS:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
      - BLiPS/BLiPS/Models
      - BLiPS/BLiPS/Views
      - BLiPS/BLiPS/ViewModels
      - BLiPS/BLiPS/Services
      - BLiPS/BLiPS/Utils
      - BLiPS/BLiPS/Resources
      - BLiPS/BLiPS/BLiPSApp.swift
      - BLiPS/BLiPS/Info.plist
    resources:
      - BLiPS/BLiPS/Assets.xcassets
      - BLiPS/BLiPS/Preview Content/Preview Assets.xcassets
    info:
      path: BLiPS/BLiPS/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.blips.app
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      SWIFT_EMIT_LOC_STRINGS: YES
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      DEVELOPMENT_ASSET_PATHS: "BLiPS/BLiPS/Preview Content" 