name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run type checking
      run: npx tsc --noEmit

    - name: Build project
      run: npm run build

    - name: Run tests (if available)
      run: npm test --if-present

  tauri-build-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.0-dev \
          libjavascriptcoregtk-4.0-dev \
          libsoup-3.0-0 \
          libsoup-3.0-dev \
          libgtk-3-dev \
          libglib2.0-dev \
          libssl-dev \
          libappindicator3-dev \
          librsvg2-dev \
          pkg-config \
          build-essential \
          curl \
          wget \
          file \
          libatk1.0-dev \
          libgdk-pixbuf2.0-dev \
          libpango1.0-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxdamage-dev \
          libxext-dev \
          libxfixes-dev \
          libxi-dev \
          libxrandr-dev \
          libxrender-dev \
          libxtst-dev \
          libgtk-3-0 \
          libnotify-dev \
          libsecret-1-dev \
          libsqlite3-dev \
          libxml2-dev \
          libxslt1-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          gstreamer1.0-alsa \
          gstreamer1.0-gl \
          gstreamer1.0-gtk3 \
          gstreamer1.0-pulseaudio \
          gstreamer1.0-x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@latest

    - name: Test Tauri build
      run: npx tauri build --target x86_64-unknown-linux-gnu

  deploy:
    needs: [test, tauri-build-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 