name: Tauri Release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
          - platform: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform == 'ubuntu-22.04' && 'ubuntu-22.04' || matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libsoup-3.0-0 \
            libsoup-3.0-dev \
            libgtk-3-dev \
            libglib2.0-dev \
            libssl-dev \
            libappindicator3-dev \
            librsvg2-dev \
            pkg-config \
            build-essential \
            curl \
            wget \
            file \
            libatk1.0-dev \
            libgdk-pixbuf2.0-dev \
            libpango1.0-dev \
            libx11-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxdamage-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrandr-dev \
            libxrender-dev \
            libxtst-dev \
            libgtk-3-0 \
            libnotify-dev \
            libsecret-1-dev \
            libsqlite3-dev \
            libxml2-dev \
            libxslt1-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-alsa \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-pulseaudio \
            gstreamer1.0-x
          # Symlinks for Tauri 2.x if 4.1 .pc files are missing
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc || true
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/javascriptcoregtk-4.0.pc /usr/lib/x86_64-linux-gnu/pkgconfig/javascriptcoregtk-4.1.pc || true

      - name: Debug pkg-config files (Linux only)
        if: runner.os == 'Linux'
        run: |
          ls -l /usr/lib/x86_64-linux-gnu/pkgconfig/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Debug matrix.target
        run: echo "matrix.target is ${{ matrix.target }}"

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest

      - name: Build Tauri app
        run: npx tauri build --target ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blips-${{ matrix.platform }}-${{ matrix.target }}
          path: src-tauri/target/release/bundle/
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: matrix.platform == 'macos-latest'
        with:
          files: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/windows/*.msi
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 