name: Tauri Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
          - platform: macos-latest
            target: x86_64-apple-darwin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust dependencies
      run: |
        rustup target add ${{ matrix.target }}
        rustup show

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blips-${{ matrix.platform }}-${{ matrix.target }}
        path: src-tauri/target/release/
        if-no-files-found: error

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: matrix.platform == 'ubuntu-latest'
      with:
        files: |
          src-tauri/target/release/*.deb
          src-tauri/target/release/*.AppImage
          src-tauri/target/release/*.msi
          src-tauri/target/release/*.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 