name: Tauri Release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
          - platform: macos-latest
            target: aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-dev \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libappindicator3-dev \
            librsvg2-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Debug matrix.target
        run: echo "matrix.target is ${{ matrix.target }}"

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest

      - name: Build Tauri app
        run: npx tauri build --target ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blips-${{ matrix.platform }}-${{ matrix.target }}
          path: src-tauri/target/release/bundle/
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: matrix.platform == 'macos-latest'
        with:
          files: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/windows/*.msi
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 