name: Tauri Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust dependencies
      run: |
        rustup target add ${{ matrix.target }}
        rustup show

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blips-${{ matrix.platform }}-${{ matrix.target }}
        path: src-tauri/target/release/
        if-no-files-found: error

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: matrix.platform == 'ubuntu-latest'
      with:
        files: |
          src-tauri/target/release/*.deb
          src-tauri/target/release/*.AppImage
          src-tauri/target/release/*.msi
          src-tauri/target/release/*.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Platform-specific builds
  build-linux:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust dependencies
      run: |
        rustup target add x86_64-unknown-linux-gnu
        rustup target add aarch64-unknown-linux-gnu

    - name: Build Tauri app for Linux
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --target x86_64-unknown-linux-gnu --target aarch64-unknown-linux-gnu

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blips-linux
        path: src-tauri/target/release/
        if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Tauri app for Windows
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blips-windows
        path: src-tauri/target/release/
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust dependencies
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

    - name: Build Tauri app for macOS
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --target x86_64-apple-darwin --target aarch64-apple-darwin

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blips-macos
        path: src-tauri/target/release/
        if-no-files-found: error

  # Create release with all artifacts
  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: github.event_name == 'release'

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 